import Head from 'next/head'
import Image from 'next/image'


export default function Home() {
  return (
    <div >
      <Head>
        <title>GuitarLA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Aprendiendo Next</h1>
      <footer >
        <div>Made with ❤ from Honduras. By Daniel Reyes</div>
      </footer>
    </div>
  )
}
